---
title: 破損状態の例外のコード分析規則の CA2153 (コード分析)
description: 破損状態例外のコード分析ルールコード分析ルール CA2153 について説明します
ms.date: 02/19/2019
ms.topic: reference
author: gewarren
ms.author: gewarren
ms.openlocfilehash: 82429187b430c7c0eb0cfb3c354585e62a690bcd
ms.sourcegitcommit: 4df8e005c074ceb1f978f007b222fe253be2baf3
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 02/04/2021
ms.locfileid: "99545387"
---
# <a name="ca2153-avoid-handling-corrupted-state-exceptions"></a><span data-ttu-id="fc8f4-103">CA2153:破損状態の例外の処理を回避する</span><span class="sxs-lookup"><span data-stu-id="fc8f4-103">CA2153: Avoid handling Corrupted State Exceptions</span></span>

| | <span data-ttu-id="fc8f4-104">値</span><span class="sxs-lookup"><span data-stu-id="fc8f4-104">Value</span></span> |
|-|-|
| <span data-ttu-id="fc8f4-105">**ルール ID**</span><span class="sxs-lookup"><span data-stu-id="fc8f4-105">**Rule ID**</span></span> |<span data-ttu-id="fc8f4-106">CA2153</span><span class="sxs-lookup"><span data-stu-id="fc8f4-106">CA2153</span></span>|
| <span data-ttu-id="fc8f4-107">**カテゴリ**</span><span class="sxs-lookup"><span data-stu-id="fc8f4-107">**Category**</span></span> |[<span data-ttu-id="fc8f4-108">Microsoft.Security</span><span class="sxs-lookup"><span data-stu-id="fc8f4-108">Microsoft.Security</span></span>](security-warnings.md)|
| <span data-ttu-id="fc8f4-109">**修正が中断または非対応になっています**</span><span class="sxs-lookup"><span data-stu-id="fc8f4-109">**Fix is breaking or non-breaking**</span></span> |<span data-ttu-id="fc8f4-110">なし</span><span class="sxs-lookup"><span data-stu-id="fc8f4-110">Non-breaking</span></span>|

## <a name="cause"></a><span data-ttu-id="fc8f4-111">原因</span><span class="sxs-lookup"><span data-stu-id="fc8f4-111">Cause</span></span>

<span data-ttu-id="fc8f4-112">[破損状態の例外 (CSEs)](/archive/msdn-magazine/2009/february/clr-inside-out-handling-corrupted-state-exceptions) は、メモリの破損がプロセス内に存在することを示します。</span><span class="sxs-lookup"><span data-stu-id="fc8f4-112">[Corrupted State Exceptions (CSEs)](/archive/msdn-magazine/2009/february/clr-inside-out-handling-corrupted-state-exceptions) indicate that memory corruption exists in your process.</span></span> <span data-ttu-id="fc8f4-113">プロセスをクラッシュさせるのではなくこれらの例外をキャッチすることは、攻撃者が破損したメモリ領域にセキュリティ上の弱点を見出すことができた場合に、セキュリティ上の脆弱性となる可能性があります。</span><span class="sxs-lookup"><span data-stu-id="fc8f4-113">Catching these rather than allowing the process to crash can lead to security vulnerabilities if an attacker can place an exploit into the corrupted memory region.</span></span>

## <a name="rule-description"></a><span data-ttu-id="fc8f4-114">規則の説明</span><span class="sxs-lookup"><span data-stu-id="fc8f4-114">Rule description</span></span>

<span data-ttu-id="fc8f4-115">CSE は、プロセスが破損状態にあり、システムによってキャッチされていないことを示します。</span><span class="sxs-lookup"><span data-stu-id="fc8f4-115">CSE indicates that the state of a process has been corrupted and not caught by the system.</span></span> <span data-ttu-id="fc8f4-116">破損状態のシナリオでは、属性を使用してメソッドをマークした場合にのみ、一般的なハンドラーが例外をキャッチし <xref:System.Runtime.ExceptionServices.HandleProcessCorruptedStateExceptionsAttribute?displayProperty=fullName> ます。</span><span class="sxs-lookup"><span data-stu-id="fc8f4-116">In the corrupted state scenario, a general handler only catches the exception if you mark your method with the <xref:System.Runtime.ExceptionServices.HandleProcessCorruptedStateExceptionsAttribute?displayProperty=fullName> attribute.</span></span> <span data-ttu-id="fc8f4-117">既定では、 [共通言語ランタイム (CLR)](../../../standard/clr.md) は、cses の catch ハンドラーを呼び出しません。</span><span class="sxs-lookup"><span data-stu-id="fc8f4-117">By default, the [Common Language Runtime (CLR)](../../../standard/clr.md) does not invoke catch handlers for CSEs.</span></span>

<span data-ttu-id="fc8f4-118">最も安全なオプションは、この種の例外をキャッチせずにプロセスをクラッシュさせることです。</span><span class="sxs-lookup"><span data-stu-id="fc8f4-118">The safest option is to allow the process to crash without catching these kinds of exceptions.</span></span> <span data-ttu-id="fc8f4-119">ログコードでも、攻撃者はメモリ破損のバグを悪用できます。</span><span class="sxs-lookup"><span data-stu-id="fc8f4-119">Even logging code can allow attackers to exploit memory corruption bugs.</span></span>

<span data-ttu-id="fc8f4-120">この警告は、すべての例外をキャッチする汎用ハンドラーを使用して、または例外パラメーターを指定せずに、CSEs をキャッチするときにトリガーさ `catch (System.Exception e)` `catch` れます。</span><span class="sxs-lookup"><span data-stu-id="fc8f4-120">This warning triggers when catching CSEs with a general handler that catches all exceptions, for example, `catch (System.Exception e)` or `catch` with no exception parameter.</span></span>

## <a name="how-to-fix-violations"></a><span data-ttu-id="fc8f4-121">違反の修正方法</span><span class="sxs-lookup"><span data-stu-id="fc8f4-121">How to fix violations</span></span>

<span data-ttu-id="fc8f4-122">この警告を解決するには、次のいずれかの操作を行います。</span><span class="sxs-lookup"><span data-stu-id="fc8f4-122">To resolve this warning, do one of the following:</span></span>

- <span data-ttu-id="fc8f4-123"><xref:System.Runtime.ExceptionServices.HandleProcessCorruptedStateExceptionsAttribute> 属性を削除してください。</span><span class="sxs-lookup"><span data-stu-id="fc8f4-123">Remove the <xref:System.Runtime.ExceptionServices.HandleProcessCorruptedStateExceptionsAttribute> attribute.</span></span> <span data-ttu-id="fc8f4-124">これにより、CSEs が catch ハンドラーに渡されない既定の実行時の動作に戻ります。</span><span class="sxs-lookup"><span data-stu-id="fc8f4-124">This reverts to the default run-time behavior where CSEs are not passed to catch handlers.</span></span>

- <span data-ttu-id="fc8f4-125">特定の例外の種類をキャッチするハンドラーではなく汎用 catch ハンドラーを削除します。</span><span class="sxs-lookup"><span data-stu-id="fc8f4-125">Remove the general catch handler in preference of handlers that catch specific exception types.</span></span> <span data-ttu-id="fc8f4-126">これには、ハンドラーコードが安全に処理できる (まれ) と仮定して、CSEs を含めることができます。</span><span class="sxs-lookup"><span data-stu-id="fc8f4-126">This may include CSEs, assuming the handler code can safely handle them (rare).</span></span>

- <span data-ttu-id="fc8f4-127">例外を呼び出し元に渡し、実行中のプロセスを終了する必要がある catch ハンドラーで CSE を再スローします。</span><span class="sxs-lookup"><span data-stu-id="fc8f4-127">Rethrow the CSE in the catch handler, which passes the exception to the caller and should result in ending the running process.</span></span>

## <a name="when-to-suppress-warnings"></a><span data-ttu-id="fc8f4-128">警告を非表示にする場合</span><span class="sxs-lookup"><span data-stu-id="fc8f4-128">When to suppress warnings</span></span>

<span data-ttu-id="fc8f4-129">この規則による警告は抑制しないでください。</span><span class="sxs-lookup"><span data-stu-id="fc8f4-129">Do not suppress a warning from this rule.</span></span>

## <a name="pseudo-code-example"></a><span data-ttu-id="fc8f4-130">擬似コードの例</span><span class="sxs-lookup"><span data-stu-id="fc8f4-130">Pseudo-code example</span></span>

### <a name="violation"></a><span data-ttu-id="fc8f4-131">違反</span><span class="sxs-lookup"><span data-stu-id="fc8f4-131">Violation</span></span>

<span data-ttu-id="fc8f4-132">次の擬似コードでは、このルールにより検出されたパターンを示しています。</span><span class="sxs-lookup"><span data-stu-id="fc8f4-132">The following pseudo-code illustrates the pattern detected by this rule.</span></span>

```csharp
[HandleProcessCorruptedStateExceptions]
// Method that handles CSE exceptions.
void TestMethod1()
{
    try
    {
        FileStream fileStream = new FileStream("name", FileMode.Create);
    }
    catch (Exception e)
    {
        // Handle exception.
    }
}
```

### <a name="solution-1---remove-the-attribute"></a><span data-ttu-id="fc8f4-133">解決策 1-属性を削除する</span><span class="sxs-lookup"><span data-stu-id="fc8f4-133">Solution 1 - remove the attribute</span></span>

<span data-ttu-id="fc8f4-134">属性を削除すると、 <xref:System.Runtime.ExceptionServices.HandleProcessCorruptedStateExceptionsAttribute> メソッドによって破損状態の例外が処理されなくなります。</span><span class="sxs-lookup"><span data-stu-id="fc8f4-134">Removing the <xref:System.Runtime.ExceptionServices.HandleProcessCorruptedStateExceptionsAttribute> attribute ensures that Corrupted State Exceptions are not handled by your method.</span></span>

```csharp
void TestMethod1()
{
    try
    {
        FileStream fileStream = new FileStream("name", FileMode.Create);
    }
    catch (Exception e)
    {
        // Handle exception.
    }
}
```

### <a name="solution-2---catch-specific-exceptions"></a><span data-ttu-id="fc8f4-135">解決策 2-特定の例外をキャッチする</span><span class="sxs-lookup"><span data-stu-id="fc8f4-135">Solution 2 - catch specific exceptions</span></span>

<span data-ttu-id="fc8f4-136">汎用 catch ハンドラーを削除し、特定の例外の種類のみをキャッチします。</span><span class="sxs-lookup"><span data-stu-id="fc8f4-136">Remove the general catch handler and catch only specific exception types.</span></span>

```csharp
void TestMethod1()
{
    try
    {
        FileStream fileStream = new FileStream("name", FileMode.Create);
    }
    catch (IOException e)
    {
        // Handle IOException.
    }
    catch (UnauthorizedAccessException e)
    {
        // Handle UnauthorizedAccessException.
    }
}
```

### <a name="solution-3---rethrow"></a><span data-ttu-id="fc8f4-137">解決策 3-再スロー</span><span class="sxs-lookup"><span data-stu-id="fc8f4-137">Solution 3 - rethrow</span></span>

<span data-ttu-id="fc8f4-138">例外を再スローします。</span><span class="sxs-lookup"><span data-stu-id="fc8f4-138">Rethrow the exception.</span></span>

```csharp
[HandleProcessCorruptedStateExceptions]
void TestMethod1()
{
    try
    {
        FileStream fileStream = new FileStream("name", FileMode.Create);
    }
    catch (Exception e)
    {
        // Rethrow the exception.
        throw;
    }
}
```
